/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas;

import IntegracionApi.TMDBApiAdapter;
import IntegracionApi.TMDBResponse;
import dtos.ActorDTO;
import dtos.PeliculasDTO;
import dtos.UsuarioDTO;
import java.awt.Image;
import java.net.URL;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import interfaces.IPeliculaService;
import servicios.PeliculaService;

/**
 *
 * @author golea
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    private IPeliculaService peliculaService;

    public Principal(UsuarioDTO usuario) {
        initComponents();
        lblnombredeUsuario.setText(usuario.getNombre());
        this.peliculaService = new servicios.PeliculaService();
        cargarCaratulas();
    }

    private void cargarCaratulas() {
        List<PeliculasDTO> lista = peliculaService.obtenerUltimasPeliculas();

        javax.swing.JLabel[] labelsImagen = {
            imgCaratulaPelicula,
            imgCaratulaPelicula1,
            imgCaratulaPelicula2,
            imgCaratulaPelicula3
        };

        javax.swing.JButton[] labelsTitulo = {
            btnNombrePeli0, 
            btnNombrePeli1,
            btnNombrePeli2,
            btnNombrePeli3
        };

        for (int i = 0; i < lista.size() && i < labelsImagen.length; i++) {
            PeliculasDTO peli = lista.get(i);

            if (peli.getPosterPath() != null && !peli.getPosterPath().isEmpty()) {
                String urlCompleta = "https://image.tmdb.org/t/p/w500" + peli.getPosterPath();
                pintarImagen(labelsImagen[i], urlCompleta);
            }

            if (i < labelsTitulo.length) {
                labelsTitulo[i].setText(peli.getTitulo());
                labelsTitulo[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            }
        }
    }

    private void pintarImagen(JLabel lbl, String urlStr) {
        try {
            URL url = new URL(urlStr);
            Image img = ImageIO.read(url);

            int ancho = lbl.getWidth() > 0 ? lbl.getWidth() : 133;
            int alto = lbl.getHeight() > 0 ? lbl.getHeight() : 123;
            Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            lbl.setIcon(new ImageIcon(imgEscalada));
            lbl.setText("");
        } catch (Exception e) {
            System.err.println("Error al cargar imagen: " + e.getMessage());
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgCaratulaPelicula = new javax.swing.JLabel();
        imgCaratulaPelicula1 = new javax.swing.JLabel();
        imgCaratulaPelicula2 = new javax.swing.JLabel();
        imgCaratulaPelicula3 = new javax.swing.JLabel();
        lblEstrenos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblActor1 = new javax.swing.JLabel();
        lblActor2 = new javax.swing.JLabel();
        lblActor3 = new javax.swing.JLabel();
        lblActor4 = new javax.swing.JLabel();
        lblActor5 = new javax.swing.JLabel();
        lblActor6 = new javax.swing.JLabel();
        btnReseñas = new javax.swing.JButton();
        lblnombredeUsuario = new javax.swing.JLabel();
        btnBuscarPelicula = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnPlaylist = new javax.swing.JButton();
        btnNombrePeli0 = new javax.swing.JButton();
        btnNombrePeli1 = new javax.swing.JButton();
        btnNombrePeli2 = new javax.swing.JButton();
        btnNombrePeli3 = new javax.swing.JButton();

        imgCaratulaPelicula.setText("jLabel1");

        imgCaratulaPelicula1.setText("jLabel1");

        imgCaratulaPelicula2.setText("jLabel1");

        imgCaratulaPelicula3.setText("jLabel1");

        lblEstrenos.setText("ESTRENOS:");

        jLabel1.setText("Actores Recientes:");

        lblActor1.setText("ActorNombre1");

        lblActor2.setText("ActorNombre2");

        lblActor3.setText("ActorNombre3");

        lblActor4.setText("ActorNombre4");

        lblActor5.setText("ActorNombre5");

        lblActor6.setText("ActorNombre6");

        btnReseñas.setText("Reseñas");
        btnReseñas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReseñasActionPerformed(evt);
            }
        });

        lblnombredeUsuario.setText("Nombre de Usuario");

        btnBuscarPelicula.setText("Buscar Pelicula");
        btnBuscarPelicula.setToolTipText("");

        jTextField1.setText("Introduce nombre de pelicula");

        btnPlaylist.setText("Playlist");

        btnNombrePeli0.setText("jButton1");

        btnNombrePeli1.setText("jButton1");

        btnNombrePeli2.setText("jButton1");

        btnNombrePeli3.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblEstrenos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblActor2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblActor3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblActor4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(174, 174, 174)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblActor5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblActor6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlaylist)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(74, 90, Short.MAX_VALUE)
                        .addComponent(imgCaratulaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(imgCaratulaPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(imgCaratulaPelicula2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(imgCaratulaPelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReseñas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnombredeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnNombrePeli0, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnNombrePeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnNombrePeli2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnNombrePeli3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReseñas)
                    .addComponent(lblnombredeUsuario)
                    .addComponent(btnBuscarPelicula)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlaylist))
                .addGap(67, 67, 67)
                .addComponent(lblEstrenos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgCaratulaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgCaratulaPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgCaratulaPelicula2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgCaratulaPelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNombrePeli0)
                    .addComponent(btnNombrePeli1)
                    .addComponent(btnNombrePeli2)
                    .addComponent(btnNombrePeli3))
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActor1)
                    .addComponent(lblActor4)
                    .addComponent(lblActor5))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActor3)
                    .addComponent(lblActor2)
                    .addComponent(lblActor6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReseñasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReseñasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReseñasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPelicula;
    private javax.swing.JButton btnNombrePeli0;
    private javax.swing.JButton btnNombrePeli1;
    private javax.swing.JButton btnNombrePeli2;
    private javax.swing.JButton btnNombrePeli3;
    private javax.swing.JButton btnPlaylist;
    private javax.swing.JButton btnReseñas;
    private javax.swing.JLabel imgCaratulaPelicula;
    private javax.swing.JLabel imgCaratulaPelicula1;
    private javax.swing.JLabel imgCaratulaPelicula2;
    private javax.swing.JLabel imgCaratulaPelicula3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblActor1;
    private javax.swing.JLabel lblActor2;
    private javax.swing.JLabel lblActor3;
    private javax.swing.JLabel lblActor4;
    private javax.swing.JLabel lblActor5;
    private javax.swing.JLabel lblActor6;
    private javax.swing.JLabel lblEstrenos;
    private javax.swing.JLabel lblnombredeUsuario;
    // End of variables declaration//GEN-END:variables
}
