/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas;

import dtos.UsuarioDTO;
import interfaces.IUsuarioService;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.AbstractBorder;
import servicios.UsuarioService;

/**
 *
 * @author golea
 */
public class RegistroUsuario extends javax.swing.JPanel {

    private IUsuarioService usuarioService;

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
        // Inicializamos el servicio que contiene la lógica de validación 
        this.usuarioService = new UsuarioService();
        personalizarDiseñoAgrandado();
        // Limpiamos los campos de texto iniciales
        txtNombreUsuario.setText("");
        txtCorreoElectronico.setText("");
        txtContrasena.setText("");
    }

    private void personalizarDiseñoAgrandado() {
        // Fondo igual al de inicio de sesión
        this.setBackground(Color.WHITE);

        // --- CONFIGURACIÓN DE ESCALA (Igual a InicioSesion) ---
        Dimension dimensionCampos = new Dimension(350, 50);
        Dimension dimensionBotones = new Dimension(350, 55);
        Font fuenteLabels = new Font("SansSerif", Font.PLAIN, 18);
        Font fuenteCampos = new Font("SansSerif", Font.PLAIN, 18);
        Font fuenteBotones = new Font("SansSerif", Font.BOLD, 18);

        // Estilo de etiquetas
        lblUsuario.setFont(fuenteLabels);
        lblCorreoElectronico.setFont(fuenteLabels);
        lblContrasena.setFont(fuenteLabels);

        // Borde redondeado (Corregido con draw para poder escribir)
        AbstractBorder roundedBorder = new AbstractBorder() {
            @Override
            public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(Color.GRAY);
                g2.draw(new RoundRectangle2D.Double(x, y, width - 1, height - 1, 20, 20));
                g2.dispose();
            }
        };

        // Aplicar a campos de texto
        configurarCampo(txtNombreUsuario, dimensionCampos, fuenteCampos, roundedBorder);
        configurarCampo(txtCorreoElectronico, dimensionCampos, fuenteCampos, roundedBorder);
        configurarCampo(txtContrasena, dimensionCampos, fuenteCampos, roundedBorder);

        // Configurar Botones
        configurarBotonEstilo(btnCrearCuenta, new Color(50, 50, 50), Color.WHITE, dimensionBotones, fuenteBotones);
        configurarBotonEstilo(btnregresar, new Color(220, 220, 220), Color.BLACK, dimensionBotones, fuenteBotones);

        // Forzar actualización de layout
        this.revalidate();
        this.repaint();
    }

    private void configurarCampo(JTextField campo, Dimension dim, Font fuente, AbstractBorder borde) {
        campo.setPreferredSize(dim);
        campo.setFont(fuente);
        campo.setBackground(Color.WHITE);
        // Añadimos un margen interno para que el texto no toque el borde
        campo.setBorder(BorderFactory.createCompoundBorder(borde, BorderFactory.createEmptyBorder(5, 10, 5, 10)));
    }

    private void configurarBotonEstilo(JButton btn, Color fondo, Color texto, Dimension dim, Font fuente) {
        btn.setBackground(fondo);
        btn.setForeground(texto);
        btn.setPreferredSize(dim);
        btn.setFont(fuente);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void limpiarCampos() {
        txtNombreUsuario.setText("");
        txtCorreoElectronico.setText("");
        txtContrasena.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        lblUsuario.setText("Nombre Usuario");

        lblCorreoElectronico.setText("Correo Electronico");

        txtCorreoElectronico.setText("jTextField1");

        lblContrasena.setText("Contrasena");

        txtContrasena.setText("jTextField1");

        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnregresar.setText("Regresar ");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnregresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContrasena)
                    .addComponent(lblCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreUsuario)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContrasena)
                    .addComponent(txtCorreoElectronico))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCorreoElectronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnCrearCuenta)
                .addGap(18, 18, 18)
                .addComponent(btnregresar)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        // 1. Capturar datos de la interfaz
        String nombre = txtNombreUsuario.getText().trim();
        String email = txtCorreoElectronico.getText().trim();
        String password = txtContrasena.getText().trim();

        // 2. Validación simple de campos vacíos en la UI
        if (nombre.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Crear el DTO para enviar al servicio
        UsuarioDTO nuevoUsuario = new UsuarioDTO();
        nuevoUsuario.setNombre(nombre);
        nuevoUsuario.setEmail(email);
        nuevoUsuario.setPassword(password);

        try {
            // 4. Llamar al servicio. 
            // Este método ya verifica si el email es válido y si ya está registrado.
            usuarioService.registrar(nuevoUsuario);

            JOptionPane.showMessageDialog(this, "¡Usuario registrado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Opcional: Limpiar campos o navegar al login
            limpiarCampos();

        } catch (Exception e) {
            // 5. Manejo de errores (Email inválido o Usuario ya existe) 
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (parentWindow instanceof Iniciosesion) {
            Iniciosesion login = new Iniciosesion();
            login.setVisible(true);
            parentWindow.dispose();
        }
    }//GEN-LAST:event_btnregresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
